

@baseUrl = http://localhost:3000/api
@contentType = application/json

### 用户登录

# @name login
@auth = {{login.response.body.$.token}}
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "username": "wcj",
  "password": "123456"
}

### 员工信息列表

@userId = {{getList.response.body.$[0].id}}

# @name getList
GET {{baseUrl}}/user/staff?page=1&per_page=30
Content-Type: {{contentType}}
Authorization: token {{auth}}


### 更新员工信息

PUT {{baseUrl}}/user/staff
Content-Type: {{contentType}}
Authorization: token {{auth}}

{
  "id": "{{userId}}",
  "name": "周杰伦",
  "mobile": "1366666{{$randomInt 5 200}}",
  "age": {{$randomInt 5 200}}
}


### 添加员工信息

POST {{baseUrl}}/user/staff
Content-Type: {{contentType}}
Authorization: token {{auth}}

{
  "name": "周杰伦{{$randomInt 1 200}}",
  "mobile": "136666{{$randomInt 5 200}}6666",
  "age": 18
}

### 获取员工信息

GET {{baseUrl}}/user/staff/{{userId}}
Content-Type: {{contentType}}
Authorization: token {{auth}}

### 删除员工信息

DELETE {{baseUrl}}/user/staff/{{userId}}?token={{auth}}
Content-Type: application/json