name: Build & Deploy
on:
  push:
    branches:
      - dev
env:
  SKIP_PREFLIGHT_CHECK: true
jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Look Changelog
      uses: jaywcjlove/changelog-generator@v1.5.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filter-author: (renovate-bot|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - run: npm install
    - run: npm run build
    - run: npm run type-check

    - name: example @example/basic
      working-directory: example/basic
      run: npm run build && npm run coverage

    - name: example @example/express
      working-directory: example/express
      run: npm run build

    - name: example @example/hapi
      working-directory: example/hapi
      run: npm run build

    - name: example @example/express-typeorm
      working-directory: example/express-typeorm
      run: npm run build

    - name: example @example/koa
      working-directory: example/koa
      run: npm run build

    - name: example @example/react-component
      working-directory: example/react-component
      run: npm run build && npm run doc

    - name: example @example/react-component-tsx
      working-directory: example/react-component-tsx
      run: |
        npm run build
        npm run doc
        cd lib/
        ls -al

    - name: example @example/transform-typescript
      working-directory: example/transform-typescript
      run: npm run build

    - name: example @example/umd
      working-directory: example/umd
      run: npm run build

    - name: example @example/vue
      working-directory: example/vue
      run: npm run build
